#!/bin/bash

FACTORY_PRODUCTS="PHY_SINGLE_LINK PHY_ILAG IPVPN_CORE IPVPN_SAP ELAN_CORE ELAN_SAP PHY_ESILAG ELINE_CORE ELINE_SAP IP_SAP"
COMPONENTS="RBH_RPD RBH_CMTS RBH_CMTS_INET RBH_CMTS_ABR_MC RTL_PROV RTL_MGT RTL_INET RTL_VOIP INF_DHCPTRAFFIC INF_MGT RTL_IPTV RTL_CGN"
CFSES="TN_RBH_RPD_ACCESS TN_RBH_CMTS_ACCESS TN_RBH_CMTS_CORE TN_B2C_OLT_ACCESS TN_B2C_XDSLAM_ACCESS TN_CMTS_ACCESS"
TABLES="LKT_TND_FACTORY_PRODUCT_PARAMETERS LKT_MANDATORY_PARAM_CHECK LKT_TND_ENUM_PARAM_CHECK LKT_TND_CRAMER_COMMAND_VALIDATION LKT_TND_CRAMER_QUERY_SERVICE LKT_TND_CRAMER_IDENTIFY_SERVICE LKT_TND_CRAMER_SUBORDERS LKT_TND_STABLENET"

if [ $# -ne 1 ]; then
	echo "Usage: recreate_all_jsons.sh <XLS-FILE>"
	exit 1
fi
XLS=$1
if [ ! -f "$XLS" ]; then
	echo "No such file: $XLS"
	exit 1
fi
for fp in $FACTORY_PRODUCTS; do
    python ./excel2json.py -t $fp "$XLS"
done
for com in $COMPONENTS $CFSES; do
    python ./extract_cfs_param_table.py "$XLS" $com
done
