#!/bin/bash

# This file defines the components of TND and is used by other scripts
FACTORY_PRODUCTS="ELAN_CORE ELAN_SAP ELINE_CORE ELINE_SAP IP_SAP IPVPN_CORE IPVPN_SAP PHY_ESILAG PHY_ILAG PHY_SINGLE_LINK"
COMPONENTS="RBH_RPD RBH_CMTS RBH_CMTS_INET RBH_CMTS_ABR_MC RTL_PROV RTL_MGT RTL_INET RTL_VOIP INF_DHCPTRAFFIC INF_MGT RTL_IPTV RTL_CGN MBH_OAM MBH_OAM_MAD MBH_S1_4G MBH_S1_4G_MAD MBH_S1_5G MBH_S1_5G_MAD MBH_TLMGT MBH_TLMGT_MAD MBH_UPCP MBH_UPCP_MAD"
CFSES="TN_RBH_RPD_ACCESS TN_RBH_CMTS_ACCESS TN_RBH_CMTS_CORE TN_B2C_OLT_ACCESS TN_B2C_XDSLAM_ACCESS TN_CMTS_ACCESS TN_MBH_3G TN_MBH_4G5G TN_MBH_MAD TN_MBH_MSA"
